version: '3.8'

services:
  main:
    build: 
      context: ./docker/haproxy
      dockerfile: Dockerfile
    image: main:latest
    env_file: .env
    ports:
      - 3000:3000
    depends_on:
      - backend
      - frontend
    networks:
      - frontend
      - backend
  
  backend:
    build: 
      context: .
      dockerfile: docker/backend/Dockerfile
    image: backend:latest
    env_file: .env
    volumes:
      - uploads:/app/uploads
    depends_on:
      - database
    networks:
      - backend
      - database

  frontend:
    build: 
      context: .
      dockerfile: docker/frontend/Dockerfile
    image: frontend:latest
    env_file: .env
    networks:
      - frontend

  
  
  
  database:
    image: postgres:16-alpine
    volumes:
      - pg-data:/var/lib/postgresql/data
    env_file: .env
    networks:
      - backend


volumes:
  pg-data:
  uploads:


networks:
  database:
  frontend:
  backend:
