version: '3.8'

services:
  main:
    build: 
      context: ./docker/haproxy
      dockerfile: Dockerfile
    env_file: .env
    ports:
      - 3000:3000


  frontend:
    build:
      context: ./docker/node
      dockerfile: Dockerfile
    volumes:
      - ./src:/app
    working_dir: /app/frontend
    command: npm run dev
    env_file: .env
    ports:
      - 3001:3000


  backend:
    build:
      context: ./docker/node
      dockerfile: Dockerfile
    volumes:
      - ./src:/app
      - uploads:/app/uploads
    working_dir: /app/backend
    command: npm run start:dev
    env_file: .env
    ports: 
      - 3002:3000
    depends_on:
      - database

  database:
    image: postgres:16
    volumes:
      - pg-data:/var/lib/postgresql/data
    env_file: .env
    ports:
      - 5432:5432


volumes:
  pg-data:
  uploads: