name: CD

on:
    pull_request:
        branches: [ "master" ]

jobs:
    build_and_deploy:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Use Node.js
              uses: actions/setup-node@v3
              with:
                node-version-file: '.nvmrc'
                cache: 'npm'
                cache-dependency-path: './src/package-lock.json'
            - name: Install deps
              run: cd src/deployer && npm ci
            - name: Setup ssh
              run: cd src/deployer && (echo "${{ secrets.SSH_PRIVATE_KEY }}" | npm run start -- ssh ${{ secrets.SERVER_IP }} ${{ secrets.SERVER_USER }} ${{ secrets.SERVER_PORT }})
            - name: Build images
              run: docker compose -f docker-compose.prod.yaml build
            - name: Deploy
              run: cd src/deployer && npm run start -- copy-images meet-hub
            