name: CD

on:
    pull_request:
        branches: [ "master" ]

jobs:
    build_and_deploy:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Setup key
              run: |
                mkdir ~/.ssh
                echo "${{ secrets.SSH_PRIVATE_KEY }}" >> ~/.ssh/private_key
            - name: Configure ssh
              run: ./docker/configure.sh ${{ secrets.SERVER_IP }} ${{ secrets.SERVER_USER }} ${{ secrets.SERVER_PORT }}
            - name: Test connection
              run: ssh server 'echo "test connection"'
            - name: Build containers
              run: docker compose -f docker-compose.prod.yaml build
            - name: Copy containers to server and compose up
              run: ./docker/dockersend.sh   
            