name: CD

on:
    pull_request:
        branches: [ "master" ]

jobs:
    build_and_deploy:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Configure ssh
              run: >
               cat > ~/.ssh/config << EOF 
               Host server
                 HostName ${{ secrets.SERVER_IP }}
                 User ${{ secrets.SERVER_USER }}
                 Port ${{ secrets.SERVER_PORT }}
                 PubKeyAuthentication yes
                 IdentityFile ~/.ssh/deploy_private_key
               EOF
            - name: Setup key
              run: >
                cat > ~/.ssh/deploy_private_key << EOF ${{ secrets.SSH_PRIVATE_KEY }} EOF
            - name: Test connection
              run: ssh server 'echo "hello world"'
    
                
            # - name: Build containers
            #   run: docker compose -f docker-compose.prod.yaml build
            # - name: Copy containers to server and compose up
            #   run: ./docker/dockersend.sh   
            