name: CD

on:
    pull_request:
        branches: [ "master" ]

jobs:
    build_and_deploy:
        runs-on: ubuntu-latest
        env:
          KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        steps:
            - uses: actions/checkout@v4
            - name: Use Node.js
              uses: actions/setup-node@v3
              with:
                node-version-file: '.nvmrc'
                cache: 'npm'
                cache-dependency-path: './src/package-lock.json'
            - name: Install deps
              run: cd src/deployer && npm ci
            - name: Setup ssh
              run: cd src/deployer && npm run start -- ssh ${{ secrets.SERVER_IP }} ${{ secrets.SERVER_USER }} ${{ secrets.SERVER_PORT }} KEY
            