name: CD

on:
    pull_request:
        branches: [ "master" ]

jobs:
    build_and_deploy:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Configure ssh
              run: ./docker/configure.sh ${{ secrets.SERVER_IP }} ${{ secrets.SERVER_USER }} ${{ secrets.SERVER_PORT }}
            - name: Setup key
              run: >
                cat > ~/.ssh/private_key << EOF ${{ secrets.SSH_PRIVATE_KEY }} EOF
            - name: Test connection
              run: ssh server 'echo "hello world"'
    
                
            # - name: Build containers
            #   run: docker compose -f docker-compose.prod.yaml build
            # - name: Copy containers to server and compose up
            #   run: ./docker/dockersend.sh   
            