name: CI

on: 
    pull_request:
        branches: [ "master" ]

defaults:
    run:
      working-directory: ./src 

jobs:
    lint:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Use Node.js
              uses: actions/setup-node@v3
              with:
                node-version-file: '.nvmrc'
                cache: 'npm'
                cache-dependency-path: './src/package-lock.json'
            - run: npm ci
            - run: npm run lint
    
    type-check:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Use Node.js
              uses: actions/setup-node@v3
              with:
                node-version-file: '.nvmrc'
                cache: 'npm'
                cache-dependency-path: './src/package-lock.json'
            - run: npm ci
            - run: npm run type-check
    backend-test:
      runs-on: ubuntu-latest
      needs: 
        - lint
        - type-check
      steps:
        - uses: actions/checkout@v4
        - name: Use Node.js
          uses: actions/setup-node@v3
          with:
            node-version-file: '.nvmrc'
            cache: 'npm'
            cache-dependency-path: './src/package-lock.json'
        - run: npm ci
        - run: cd backend && npm run test
