name: CI

on: 
    pull_request:
        branches: [ "master" ]

defaults:
    run:
      working-directory: /src 

jobs:
    lint:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Use Node.js
              uses: actions/setup-node@v3
              with:
                node-version-file: '.nvmrc'
                cache: 'npm'
            - run: npm ci
            - run: npm run lint
    
    type-check:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Use Node.js
              uses: actions/setup-node@v3
              with:
                node-version-file: '.nvmrc'
                cache: 'npm'
            - run: npm ci
            - run: npm run type-check